// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbUrQVlyBCUBiIi853lILV6yg_zSdugyc',
    appId: '1:686352032777:web:e500ccf62b411face544d8',
    messagingSenderId: '686352032777',
    projectId: 'tactile-atlas-364516',
    authDomain: 'tactile-atlas-364516.firebaseapp.com',
    storageBucket: 'tactile-atlas-364516.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtBeFFSFhGCYE7KPNDKHvfepcz_sLcKKE',
    appId: '1:686352032777:android:356689ff0f99fa45e544d8',
    messagingSenderId: '686352032777',
    projectId: 'tactile-atlas-364516',
    storageBucket: 'tactile-atlas-364516.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJnlT_hc6tAzABA4qMv3IWZy2KDaIxaDg',
    appId: '1:686352032777:ios:5a071ac190057e6de544d8',
    messagingSenderId: '686352032777',
    projectId: 'tactile-atlas-364516',
    storageBucket: 'tactile-atlas-364516.appspot.com',
    iosClientId: '686352032777-8ncr3a3423t4vi4fp3tg65do23e5ms9o.apps.googleusercontent.com',
    iosBundleId: 'com.kberen.learnFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJnlT_hc6tAzABA4qMv3IWZy2KDaIxaDg',
    appId: '1:686352032777:ios:5a071ac190057e6de544d8',
    messagingSenderId: '686352032777',
    projectId: 'tactile-atlas-364516',
    storageBucket: 'tactile-atlas-364516.appspot.com',
    iosClientId: '686352032777-8ncr3a3423t4vi4fp3tg65do23e5ms9o.apps.googleusercontent.com',
    iosBundleId: 'com.kberen.learnFirebase',
  );
}
